# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Go-Micro(v2) Dev Doc
email: mail@arch.wiki
description: >- # this means to ignore newlines until "baseurl:"
  Community dev site - getting started, docs, tutorials and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: m3oservices
github_username:  micro-community

# Aux links for the upper right navigation
aux_links:
  "micro community on GitHub":
    - "//github.com/micro-community/go-micro/-v2-doc"

footer_content: "Copyright &copy; 2020 Micro Community, Org. Powered by <a href=\"https://github.com/micro-community\">micro-community team.</a>"

#ga_tracking: UA-70478210-5

# Build settings
highlighter: rouge

# uncomment for local development
theme: just-the-docs

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

sass:
    sass_dir: _sass
include:
  - _sass/
color_scheme: m3o

# Just the docs configs, see https://pmarsceill.github.io/just-the-docs/docs/configuration/ 
logo: "/assets/images/logo.png"
search_enabled: true
heading_anchors: true
# Enable support for hyphenated search words:
# search_tokenizer_separator: /[\s/]+/

# For the search functionality to work
webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

